name: Run Python tests

on:
  pull_request:
    branches:
      - preprod
      - prod

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "Europe/Berlin"
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install rdiff-backup
        run: uv add rdiff-backup
      - name: Install dependencies
        run: uv add pytest pytest-md pytest-emoji
      - uses: pavelzw/pytest-action@v2
        with:
          emoji: false
          verbose: false
          job-summary: true